spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/restaurant-review
    username: root
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

jwt:
  secret-key: local
  expiration: 36000000
  prefix: Bearer
  header: Authorization

front: http://localhost:3000